version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: auth-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-authdb}
      POSTGRES_USER: ${POSTGRES_USER:-authuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-authpass}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:8
    container_name: auth-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"

volumes:
  pgdata:
  redisdata:
